# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T01:08:14+00:00

from __future__ import annotations

from enum import Enum
from typing import Dict, List, Optional

from pydantic import BaseModel, Field, RootModel


class Channel(BaseModel):
    id: Optional[str] = Field(
        None, description="The unique public identifier for the candidate's channel."
    )
    type: Optional[str] = Field(
        None,
        description='The type of channel. The following is a list of types of channels, but is not exhaustive. More channel types may be added at a later time. One of: GooglePlus, YouTube, Facebook, Twitter',
    )


class LevelEnum(Enum):
    international = 'international'
    country = 'country'
    administrativeArea1 = 'administrativeArea1'
    regional = 'regional'
    administrativeArea2 = 'administrativeArea2'
    locality = 'locality'
    subLocality1 = 'subLocality1'
    subLocality2 = 'subLocality2'
    special = 'special'


class Role(Enum):
    headOfState = 'headOfState'
    headOfGovernment = 'headOfGovernment'
    deputyHeadOfGovernment = 'deputyHeadOfGovernment'
    governmentOfficer = 'governmentOfficer'
    executiveCouncil = 'executiveCouncil'
    legislatorUpperBody = 'legislatorUpperBody'
    legislatorLowerBody = 'legislatorLowerBody'
    highestCourtJudge = 'highestCourtJudge'
    judge = 'judge'
    schoolBoard = 'schoolBoard'
    specialPurposeOfficer = 'specialPurposeOfficer'
    otherRole = 'otherRole'


class DivisionSearchResult(BaseModel):
    aliases: Optional[List[str]] = Field(
        None,
        description='Other Open Civic Data identifiers that refer to the same division -- for example, those that refer to other political divisions whose boundaries are defined to be coterminous with this one. For example, ocd-division/country:us/state:wy will include an alias of ocd-division/country:us/state:wy/cd:1, since Wyoming has only one Congressional district.',
    )
    name: Optional[str] = Field(None, description='The name of the division.')
    ocdId: Optional[str] = Field(
        None, description='The unique Open Civic Data identifier for this division'
    )


class ShapeLookupBehavior(Enum):
    shapeLookupDefault = 'shapeLookupDefault'
    shapeLookupDisabled = 'shapeLookupDisabled'
    shapeLookupEnabled = 'shapeLookupEnabled'


class Election(BaseModel):
    electionDay: Optional[str] = Field(
        None, description='Day of the election in YYYY-MM-DD format.'
    )
    id: Optional[str] = Field(None, description='The unique ID of this election.')
    name: Optional[str] = Field(
        None, description='A displayable name for the election.'
    )
    ocdDivisionId: Optional[str] = Field(
        None,
        description='The political division of the election. Represented as an OCD Division ID. Voters within these political jurisdictions are covered by this election. This is typically a state such as ocd-division/country:us/state:ca or for the midterms or general election the entire US (i.e. ocd-division/country:us).',
    )
    shapeLookupBehavior: Optional[ShapeLookupBehavior] = None


class ElectionOfficial(BaseModel):
    emailAddress: Optional[str] = Field(
        None, description='The email address of the election official.'
    )
    faxNumber: Optional[str] = Field(
        None, description='The fax number of the election official.'
    )
    name: Optional[str] = Field(
        None, description='The full name of the election official.'
    )
    officePhoneNumber: Optional[str] = Field(
        None, description='The office phone number of the election official.'
    )
    title: Optional[str] = Field(
        None, description='The title of the election official.'
    )


class ElectionsQueryResponse(BaseModel):
    elections: Optional[List[Election]] = Field(
        None, description='A list of available elections'
    )
    kind: Optional[str] = Field(
        'civicinfo#electionsQueryResponse',
        description='Identifies what kind of resource this is. Value: the fixed string "civicinfo#electionsQueryResponse".',
    )


class Scope(Enum):
    statewide = 'statewide'
    congressional = 'congressional'
    stateUpper = 'stateUpper'
    stateLower = 'stateLower'
    countywide = 'countywide'
    judicial = 'judicial'
    schoolBoard = 'schoolBoard'
    citywide = 'citywide'
    special = 'special'
    countyCouncil = 'countyCouncil'
    township = 'township'
    ward = 'ward'
    cityCouncil = 'cityCouncil'
    national = 'national'


class ElectoralDistrict(BaseModel):
    id: Optional[str] = Field(
        None,
        description='An identifier for this district, relative to its scope. For example, the 34th State Senate district would have id "34" and a scope of stateUpper.',
    )
    name: Optional[str] = Field(None, description='The name of the district.')
    scope: Optional[Scope] = Field(
        None,
        description="The geographic scope of this district. If unspecified the district's geography is not known. One of: national, statewide, congressional, stateUpper, stateLower, countywide, judicial, schoolBoard, cityWide, township, countyCouncil, cityCouncil, ward, special",
    )


class FeatureType(Enum):
    typeAny = 'typeAny'
    typeTransportation = 'typeTransportation'
    typeRoute = 'typeRoute'
    typeDeprecatedHighwayDoNotUse = 'typeDeprecatedHighwayDoNotUse'
    typeHighway = 'typeHighway'
    typeHighway1 = 'typeHighway1'
    typeHighway2 = 'typeHighway2'
    typeHighway3 = 'typeHighway3'
    typeHighway4 = 'typeHighway4'
    typeHighway5 = 'typeHighway5'
    typeHighway6 = 'typeHighway6'
    typeHighway7 = 'typeHighway7'
    typeHighway8 = 'typeHighway8'
    typeHighway9 = 'typeHighway9'
    typeBicycleRoute = 'typeBicycleRoute'
    typeTrail = 'typeTrail'
    typeSegment = 'typeSegment'
    typeRoad = 'typeRoad'
    typeRailway = 'typeRailway'
    typeStandardTrack = 'typeStandardTrack'
    typeJrTrack = 'typeJrTrack'
    typeNarrowTrack = 'typeNarrowTrack'
    typeMonorailTrack = 'typeMonorailTrack'
    typeSubwayTrack = 'typeSubwayTrack'
    typeLightRailTrack = 'typeLightRailTrack'
    typeBroadTrack = 'typeBroadTrack'
    typeHighSpeedRail = 'typeHighSpeedRail'
    typeTrolleyTrack = 'typeTrolleyTrack'
    typeFerry = 'typeFerry'
    typeFerryBoat = 'typeFerryBoat'
    typeFerryTrain = 'typeFerryTrain'
    typeVirtualSegment = 'typeVirtualSegment'
    typeIntersection = 'typeIntersection'
    typeTransit = 'typeTransit'
    typeTransitStation = 'typeTransitStation'
    typeBusStation = 'typeBusStation'
    typeTramwayStation = 'typeTramwayStation'
    typeTrainStation = 'typeTrainStation'
    typeSubwayStation = 'typeSubwayStation'
    typeFerryTerminal = 'typeFerryTerminal'
    typeAirport = 'typeAirport'
    typeAirportCivil = 'typeAirportCivil'
    typeAirportMilitary = 'typeAirportMilitary'
    typeAirportMixed = 'typeAirportMixed'
    typeHeliport = 'typeHeliport'
    typeSeaplaneBase = 'typeSeaplaneBase'
    typeAirstrip = 'typeAirstrip'
    typeCableCarStation = 'typeCableCarStation'
    typeGondolaLiftStation = 'typeGondolaLiftStation'
    typeFunicularStation = 'typeFunicularStation'
    typeSpecialStation = 'typeSpecialStation'
    typeHorseCarriageStation = 'typeHorseCarriageStation'
    typeMonorailStation = 'typeMonorailStation'
    typeSeaport = 'typeSeaport'
    typeTransitStop = 'typeTransitStop'
    typeTransitTrip = 'typeTransitTrip'
    typeTransitDeparture = 'typeTransitDeparture'
    typeTransitLeg = 'typeTransitLeg'
    typeTransitLine = 'typeTransitLine'
    typeTransitAgencyDeprecatedValue = 'typeTransitAgencyDeprecatedValue'
    typeTransitTransfer = 'typeTransitTransfer'
    typeSegmentPath = 'typeSegmentPath'
    typeRoadSign = 'typeRoadSign'
    typeIntersectionGroup = 'typeIntersectionGroup'
    typePathway = 'typePathway'
    typeRestrictionGroup = 'typeRestrictionGroup'
    typeTollCluster = 'typeTollCluster'
    typePolitical = 'typePolitical'
    typeCountry = 'typeCountry'
    typeAdministrativeArea = 'typeAdministrativeArea'
    typeAdministrativeArea1 = 'typeAdministrativeArea1'
    typeUsState = 'typeUsState'
    typeGbCountry = 'typeGbCountry'
    typeJpTodoufuken = 'typeJpTodoufuken'
    typeAdministrativeArea2 = 'typeAdministrativeArea2'
    typeGbFormerPostalCounty = 'typeGbFormerPostalCounty'
    typeGbTraditionalCounty = 'typeGbTraditionalCounty'
    typeAdministrativeArea3 = 'typeAdministrativeArea3'
    typeAdministrativeArea4 = 'typeAdministrativeArea4'
    typeAdministrativeArea5 = 'typeAdministrativeArea5'
    typeAdministrativeArea6 = 'typeAdministrativeArea6'
    typeAdministrativeArea7 = 'typeAdministrativeArea7'
    typeAdministrativeArea8 = 'typeAdministrativeArea8'
    typeAdministrativeArea9 = 'typeAdministrativeArea9'
    typeColloquialArea = 'typeColloquialArea'
    typeReservation = 'typeReservation'
    typeLocality = 'typeLocality'
    typeGbPostTown = 'typeGbPostTown'
    typeJpGun = 'typeJpGun'
    typeJpShikuchouson = 'typeJpShikuchouson'
    typeJpSubShikuchouson = 'typeJpSubShikuchouson'
    typeColloquialCity = 'typeColloquialCity'
    typeSublocality = 'typeSublocality'
    typeUsBorough = 'typeUsBorough'
    typeGbDependentLocality = 'typeGbDependentLocality'
    typeJpOoaza = 'typeJpOoaza'
    typeJpKoaza = 'typeJpKoaza'
    typeJpGaiku = 'typeJpGaiku'
    typeGbDoubleDependentLocality = 'typeGbDoubleDependentLocality'
    typeJpChiban = 'typeJpChiban'
    typeJpEdaban = 'typeJpEdaban'
    typeSublocality1 = 'typeSublocality1'
    typeSublocality2 = 'typeSublocality2'
    typeSublocality3 = 'typeSublocality3'
    typeSublocality4 = 'typeSublocality4'
    typeSublocality5 = 'typeSublocality5'
    typeNeighborhood = 'typeNeighborhood'
    typeConstituency = 'typeConstituency'
    typeDesignatedMarketArea = 'typeDesignatedMarketArea'
    typeSchoolDistrict = 'typeSchoolDistrict'
    typeLandParcel = 'typeLandParcel'
    typeDisputedArea = 'typeDisputedArea'
    typePoliceJurisdiction = 'typePoliceJurisdiction'
    typeStatisticalArea = 'typeStatisticalArea'
    typeConstituencyFuture = 'typeConstituencyFuture'
    typePark = 'typePark'
    typeGolfCourse = 'typeGolfCourse'
    typeLocalPark = 'typeLocalPark'
    typeNationalPark = 'typeNationalPark'
    typeUsNationalPark = 'typeUsNationalPark'
    typeUsNationalMonument = 'typeUsNationalMonument'
    typeNationalForest = 'typeNationalForest'
    typeProvincialPark = 'typeProvincialPark'
    typeProvincialForest = 'typeProvincialForest'
    typeCampgrounds = 'typeCampgrounds'
    typeHikingArea = 'typeHikingArea'
    typeBusiness = 'typeBusiness'
    typeGovernment = 'typeGovernment'
    typeBorderCrossing = 'typeBorderCrossing'
    typeCityHall = 'typeCityHall'
    typeCourthouse = 'typeCourthouse'
    typeEmbassy = 'typeEmbassy'
    typeLibrary = 'typeLibrary'
    typeSchool = 'typeSchool'
    typeUniversity = 'typeUniversity'
    typeEmergency = 'typeEmergency'
    typeHospital = 'typeHospital'
    typePharmacy = 'typePharmacy'
    typePolice = 'typePolice'
    typeFire = 'typeFire'
    typeDoctor = 'typeDoctor'
    typeDentist = 'typeDentist'
    typeVeterinarian = 'typeVeterinarian'
    typeTravelService = 'typeTravelService'
    typeLodging = 'typeLodging'
    typeRestaurant = 'typeRestaurant'
    typeGasStation = 'typeGasStation'
    typeParking = 'typeParking'
    typePostOffice = 'typePostOffice'
    typeRestArea = 'typeRestArea'
    typeCashMachine = 'typeCashMachine'
    typeCarRental = 'typeCarRental'
    typeCarRepair = 'typeCarRepair'
    typeShopping = 'typeShopping'
    typeGrocery = 'typeGrocery'
    typeTouristDestination = 'typeTouristDestination'
    typeEcoTouristDestination = 'typeEcoTouristDestination'
    typeBirdWatching = 'typeBirdWatching'
    typeFishing = 'typeFishing'
    typeHunting = 'typeHunting'
    typeNatureReserve = 'typeNatureReserve'
    typeTemple = 'typeTemple'
    typeChurch = 'typeChurch'
    typeGurudwara = 'typeGurudwara'
    typeHinduTemple = 'typeHinduTemple'
    typeMosque = 'typeMosque'
    typeSynagogue = 'typeSynagogue'
    typeStadium = 'typeStadium'
    typeBar = 'typeBar'
    typeMovieRental = 'typeMovieRental'
    typeCoffee = 'typeCoffee'
    typeGolf = 'typeGolf'
    typeBank = 'typeBank'
    typeDoodle = 'typeDoodle'
    typeGrounds = 'typeGrounds'
    typeAirportGrounds = 'typeAirportGrounds'
    typeBuildingGrounds = 'typeBuildingGrounds'
    typeCemetery = 'typeCemetery'
    typeHospitalGrounds = 'typeHospitalGrounds'
    typeIndustrial = 'typeIndustrial'
    typeMilitary = 'typeMilitary'
    typeShoppingCenter = 'typeShoppingCenter'
    typeSportsComplex = 'typeSportsComplex'
    typeUniversityGrounds = 'typeUniversityGrounds'
    typeDeprecatedTarmac = 'typeDeprecatedTarmac'
    typeEnclosedTrafficArea = 'typeEnclosedTrafficArea'
    typeParkingLot = 'typeParkingLot'
    typeParkingGarage = 'typeParkingGarage'
    typeOffRoadArea = 'typeOffRoadArea'
    typeBorder = 'typeBorder'
    typeBuilding = 'typeBuilding'
    typeGeocodedAddress = 'typeGeocodedAddress'
    typeNaturalFeature = 'typeNaturalFeature'
    typeTerrain = 'typeTerrain'
    typeSand = 'typeSand'
    typeBeach = 'typeBeach'
    typeDune = 'typeDune'
    typeRocky = 'typeRocky'
    typeIce = 'typeIce'
    typeGlacier = 'typeGlacier'
    typeBuiltUpArea = 'typeBuiltUpArea'
    typeVegetation = 'typeVegetation'
    typeShrubbery = 'typeShrubbery'
    typeWoods = 'typeWoods'
    typeAgricultural = 'typeAgricultural'
    typeGrassland = 'typeGrassland'
    typeTundra = 'typeTundra'
    typeDesert = 'typeDesert'
    typeSaltFlat = 'typeSaltFlat'
    typeWater = 'typeWater'
    typeOcean = 'typeOcean'
    typeBay = 'typeBay'
    typeBight = 'typeBight'
    typeLagoon = 'typeLagoon'
    typeSea = 'typeSea'
    typeStrait = 'typeStrait'
    typeInlet = 'typeInlet'
    typeFjord = 'typeFjord'
    typeLake = 'typeLake'
    typeSeasonalLake = 'typeSeasonalLake'
    typeReservoir = 'typeReservoir'
    typePond = 'typePond'
    typeRiver = 'typeRiver'
    typeRapids = 'typeRapids'
    typeDistributary = 'typeDistributary'
    typeConfluence = 'typeConfluence'
    typeWaterfall = 'typeWaterfall'
    typeSpring = 'typeSpring'
    typeGeyser = 'typeGeyser'
    typeHotSpring = 'typeHotSpring'
    typeSeasonalRiver = 'typeSeasonalRiver'
    typeWadi = 'typeWadi'
    typeEstuary = 'typeEstuary'
    typeWetland = 'typeWetland'
    typeWaterNavigation = 'typeWaterNavigation'
    typeFord = 'typeFord'
    typeCanal = 'typeCanal'
    typeHarbor = 'typeHarbor'
    typeChannel = 'typeChannel'
    typeReef = 'typeReef'
    typeReefFlat = 'typeReefFlat'
    typeReefGrowth = 'typeReefGrowth'
    typeReefExtent = 'typeReefExtent'
    typeReefRockSubmerged = 'typeReefRockSubmerged'
    typeIrrigation = 'typeIrrigation'
    typeDam = 'typeDam'
    typeDrinkingWater = 'typeDrinkingWater'
    typeCurrent = 'typeCurrent'
    typeWateringHole = 'typeWateringHole'
    typeTectonic = 'typeTectonic'
    typeWateringHoleDeprecated = 'typeWateringHoleDeprecated'
    typeVolcano = 'typeVolcano'
    typeLavaField = 'typeLavaField'
    typeFissure = 'typeFissure'
    typeFault = 'typeFault'
    typeLandMass = 'typeLandMass'
    typeContinent = 'typeContinent'
    typeIsland = 'typeIsland'
    typeAtoll = 'typeAtoll'
    typeOceanRockExposed = 'typeOceanRockExposed'
    typeCay = 'typeCay'
    typePeninsula = 'typePeninsula'
    typeIsthmus = 'typeIsthmus'
    typeElevated = 'typeElevated'
    typePeak = 'typePeak'
    typeNunatak = 'typeNunatak'
    typeSpur = 'typeSpur'
    typePass = 'typePass'
    typePlateau = 'typePlateau'
    typeRidge = 'typeRidge'
    typeRavine = 'typeRavine'
    typeCrater = 'typeCrater'
    typeKarst = 'typeKarst'
    typeCliff = 'typeCliff'
    typeVista = 'typeVista'
    typeDigitalElevationModel = 'typeDigitalElevationModel'
    typeUpland = 'typeUpland'
    typeTerrace = 'typeTerrace'
    typeSlope = 'typeSlope'
    typeContourLine = 'typeContourLine'
    typePan = 'typePan'
    typeUnstableHillside = 'typeUnstableHillside'
    typeMountainRange = 'typeMountainRange'
    typeUndersea = 'typeUndersea'
    typeSubmarineSeamount = 'typeSubmarineSeamount'
    typeSubmarineRidge = 'typeSubmarineRidge'
    typeSubmarineGap = 'typeSubmarineGap'
    typeSubmarinePlateau = 'typeSubmarinePlateau'
    typeSubmarineDeep = 'typeSubmarineDeep'
    typeSubmarineValley = 'typeSubmarineValley'
    typeSubmarineBasin = 'typeSubmarineBasin'
    typeSubmarineSlope = 'typeSubmarineSlope'
    typeSubmarineCliff = 'typeSubmarineCliff'
    typeSubmarinePlain = 'typeSubmarinePlain'
    typeSubmarineFractureZone = 'typeSubmarineFractureZone'
    typeCave = 'typeCave'
    typeRock = 'typeRock'
    typeArchipelago = 'typeArchipelago'
    typePostal = 'typePostal'
    typePostalCode = 'typePostalCode'
    typePostalCodePrefix = 'typePostalCodePrefix'
    typePremise = 'typePremise'
    typeSubPremise = 'typeSubPremise'
    typeSuite = 'typeSuite'
    typePostTown = 'typePostTown'
    typePostalRound = 'typePostalRound'
    typeMetaFeature = 'typeMetaFeature'
    typeDataSource = 'typeDataSource'
    typeLocale = 'typeLocale'
    typeTimezone = 'typeTimezone'
    typeBusinessChain = 'typeBusinessChain'
    typePhoneNumberPrefix = 'typePhoneNumberPrefix'
    typePhoneNumberAreaCode = 'typePhoneNumberAreaCode'
    typeBusinessCorridor = 'typeBusinessCorridor'
    typeAddressTemplate = 'typeAddressTemplate'
    typeTransitAgency = 'typeTransitAgency'
    typeFutureGeometry = 'typeFutureGeometry'
    typeEvent = 'typeEvent'
    typeEarthquake = 'typeEarthquake'
    typeHurricane = 'typeHurricane'
    typeWeatherCondition = 'typeWeatherCondition'
    typeTransient = 'typeTransient'
    typeEntrance = 'typeEntrance'
    typeCartographic = 'typeCartographic'
    typeHighTension = 'typeHighTension'
    typeSkiTrail = 'typeSkiTrail'
    typeSkiLift = 'typeSkiLift'
    typeSkiBoundary = 'typeSkiBoundary'
    typeWatershedBoundary = 'typeWatershedBoundary'
    typeTarmac = 'typeTarmac'
    typeWall = 'typeWall'
    typePicnicArea = 'typePicnicArea'
    typePlayGround = 'typePlayGround'
    typeTrailHead = 'typeTrailHead'
    typeGolfTeeingGround = 'typeGolfTeeingGround'
    typeGolfPuttingGreen = 'typeGolfPuttingGreen'
    typeGolfRough = 'typeGolfRough'
    typeGolfSandBunker = 'typeGolfSandBunker'
    typeGolfFairway = 'typeGolfFairway'
    typeGolfHole = 'typeGolfHole'
    typeDeprecatedGolfShop = 'typeDeprecatedGolfShop'
    typeCampingSite = 'typeCampingSite'
    typeDesignatedBarbecuePit = 'typeDesignatedBarbecuePit'
    typeDesignatedCookingArea = 'typeDesignatedCookingArea'
    typeCampfirePit = 'typeCampfirePit'
    typeWaterFountain = 'typeWaterFountain'
    typeLitterReceptacle = 'typeLitterReceptacle'
    typeLockerArea = 'typeLockerArea'
    typeAnimalEnclosure = 'typeAnimalEnclosure'
    typeCartographicLine = 'typeCartographicLine'
    typeEstablishment = 'typeEstablishment'
    typeEstablishmentGrounds = 'typeEstablishmentGrounds'
    typeEstablishmentBuilding = 'typeEstablishmentBuilding'
    typeEstablishmentPoi = 'typeEstablishmentPoi'
    typeEstablishmentService = 'typeEstablishmentService'
    typeCelestial = 'typeCelestial'
    typeRoadMonitor = 'typeRoadMonitor'
    typePublicSpacesAndMonuments = 'typePublicSpacesAndMonuments'
    typeStatue = 'typeStatue'
    typeTownSquare = 'typeTownSquare'
    typeLevel = 'typeLevel'
    typeCompound = 'typeCompound'
    typeCompoundGrounds = 'typeCompoundGrounds'
    typeCompoundBuilding = 'typeCompoundBuilding'
    typeCompoundSection = 'typeCompoundSection'
    typeTerminalPoint = 'typeTerminalPoint'
    typeRegulatedArea = 'typeRegulatedArea'
    typeLogicalBorder = 'typeLogicalBorder'
    typeDoNotUseReservedToCatchGeneratedFiles = (
        'typeDoNotUseReservedToCatchGeneratedFiles'
    )
    typeUnknown = 'typeUnknown'


class GeographicDivision(BaseModel):
    alsoKnownAs: Optional[List[str]] = Field(
        None,
        description="Any other valid OCD IDs that refer to the same division.\\n\\nBecause OCD IDs are meant to be human-readable and at least somewhat predictable, there are occasionally several identifiers for a single division. These identifiers are defined to be equivalent to one another, and one is always indicated as the primary identifier. The primary identifier will be returned in ocd_id above, and any other equivalent valid identifiers will be returned in this list.\\n\\nFor example, if this division's OCD ID is ocd-division/country:us/district:dc, this will contain ocd-division/country:us/state:dc.",
    )
    name: Optional[str] = Field(None, description='The name of the division.')
    officeIndices: Optional[List[int]] = Field(
        None,
        description='List of indices in the offices array, one for each office elected from this division. Will only be present if includeOffices was true (or absent) in the request.',
    )


class MessageSet(BaseModel):
    pass


class Level(Enum):
    international = 'international'
    country = 'country'
    administrativeArea1 = 'administrativeArea1'
    regional = 'regional'
    administrativeArea2 = 'administrativeArea2'
    locality = 'locality'
    subLocality1 = 'subLocality1'
    subLocality2 = 'subLocality2'
    special = 'special'


class Precinct(BaseModel):
    administrationRegionId: Optional[str] = Field(
        None,
        description='ID of the AdministrationRegion message for this precinct. Corresponds to LocalityId xml tag.',
    )
    contestId: Optional[List[str]] = Field(
        None, description='ID(s) of the Contest message(s) for this precinct.'
    )
    datasetId: Optional[str] = Field(
        None, description='Required. Dataset ID. What datasets our Precincts come from.'
    )
    earlyVoteSiteId: Optional[List[str]] = Field(
        None, description='ID(s) of the PollingLocation message(s) for this precinct.'
    )
    electoralDistrictId: Optional[List[str]] = Field(
        None, description='ID(s) of the ElectoralDistrict message(s) for this precinct.'
    )
    id: Optional[str] = Field(
        None, description='Required. A unique identifier for this precinct.'
    )
    mailOnly: Optional[bool] = Field(
        None, description='Specifies if the precinct runs mail-only elections.'
    )
    name: Optional[str] = Field(None, description='Required. The name of the precinct.')
    number: Optional[str] = Field(None, description='The number of the precinct.')
    ocdId: Optional[List[str]] = Field(
        None, description='Encouraged. The OCD ID of the precinct'
    )
    pollingLocationId: Optional[List[str]] = Field(
        None, description='ID(s) of the PollingLocation message(s) for this precinct.'
    )
    spatialBoundaryId: Optional[List[str]] = Field(
        None,
        description='ID(s) of the SpatialBoundary message(s) for this precinct. Used to specify a geometrical boundary of the precinct.',
    )
    splitName: Optional[str] = Field(
        None,
        description='If present, this proto corresponds to one portion of split precinct. Other portions of this precinct are guaranteed to have the same `name`. If not present, this proto represents a full precicnt.',
    )
    ward: Optional[str] = Field(
        None, description='Specifies the ward the precinct is contained within.'
    )


class SimpleAddressType(BaseModel):
    city: Optional[str] = Field(None, description='The city or town for the address.')
    line1: Optional[str] = Field(
        None, description='The street name and number of this address.'
    )
    line2: Optional[str] = Field(
        None, description='The second line the address, if needed.'
    )
    line3: Optional[str] = Field(
        None, description='The third line of the address, if needed.'
    )
    locationName: Optional[str] = Field(None, description='The name of the location.')
    state: Optional[str] = Field(
        None, description='The US two letter state abbreviation of the address.'
    )
    zip: Optional[str] = Field(
        None, description='The US Postal Zip Code of the address.'
    )


class Source(BaseModel):
    name: Optional[str] = Field(None, description='The name of the data source.')
    official: Optional[bool] = Field(
        None, description='Whether this data comes from an official government source.'
    )


class FieldXgafv(Enum):
    field_1 = '1'
    field_2 = '2'


class Alt(Enum):
    json = 'json'
    media = 'media'
    proto = 'proto'


class Levels(RootModel[List[Level]]):
    root: List[Level]


class Roles(RootModel[List[Role]]):
    root: List[Role]


class Levels1(RootModel[List[Level]]):
    root: List[Level]


class Roles1(RootModel[List[Role]]):
    root: List[Role]


class AdministrativeBody(BaseModel):
    absenteeVotingInfoUrl: Optional[str] = Field(
        None,
        description='A URL provided by this administrative body for information on absentee voting.',
    )
    ballotInfoUrl: Optional[str] = Field(
        None,
        description='A URL provided by this administrative body to give contest information to the voter.',
    )
    correspondenceAddress: Optional[SimpleAddressType] = Field(
        None, description='The mailing address of this administrative body.'
    )
    electionInfoUrl: Optional[str] = Field(
        None,
        description='A URL provided by this administrative body for looking up general election information.',
    )
    electionNoticeText: Optional[str] = Field(
        None,
        description='A last minute or emergency notification text provided by this administrative body.',
    )
    electionNoticeUrl: Optional[str] = Field(
        None,
        description='A URL provided by this administrative body for additional information related to the last minute or emergency notification.',
    )
    electionOfficials: Optional[List[ElectionOfficial]] = Field(
        None,
        description='The election officials for this election administrative body.',
    )
    electionRegistrationConfirmationUrl: Optional[str] = Field(
        None,
        description='A URL provided by this administrative body for confirming that the voter is registered to vote.',
    )
    electionRegistrationUrl: Optional[str] = Field(
        None,
        description='A URL provided by this administrative body for looking up how to register to vote.',
    )
    electionRulesUrl: Optional[str] = Field(
        None,
        description='A URL provided by this administrative body describing election rules to the voter.',
    )
    hoursOfOperation: Optional[str] = Field(
        None,
        description='A description of the hours of operation for this administrative body.',
    )
    name: Optional[str] = Field(
        None, description='The name of this election administrative body.'
    )
    physicalAddress: Optional[SimpleAddressType] = Field(
        None, description='The physical address of this administrative body.'
    )
    voter_services: Optional[List[str]] = Field(
        None,
        description='A description of the services this administrative body may provide.',
    )
    votingLocationFinderUrl: Optional[str] = Field(
        None,
        description='A URL provided by this administrative body for looking up where to vote.',
    )


class Candidate(BaseModel):
    candidateUrl: Optional[str] = Field(
        None, description="The URL for the candidate's campaign web site."
    )
    channels: Optional[List[Channel]] = Field(
        None, description='A list of known (social) media channels for this candidate.'
    )
    email: Optional[str] = Field(
        None, description="The email address for the candidate's campaign."
    )
    name: Optional[str] = Field(
        None,
        description='The candidate\'s name. If this is a joint ticket it will indicate the name of the candidate at the top of a ticket followed by a / and that name of candidate at the bottom of the ticket. e.g. "Mitt Romney / Paul Ryan"',
    )
    orderOnBallot: Optional[str] = Field(
        None,
        description='The order the candidate appears on the ballot for this contest.',
    )
    party: Optional[str] = Field(
        None, description='The full name of the party the candidate is a member of.'
    )
    phone: Optional[str] = Field(
        None, description="The voice phone number for the candidate's campaign office."
    )
    photoUrl: Optional[str] = Field(
        None, description='A URL for a photo of the candidate.'
    )


class Contest(BaseModel):
    ballotPlacement: Optional[str] = Field(
        None,
        description="A number specifying the position of this contest on the voter's ballot.",
    )
    ballotTitle: Optional[str] = Field(
        None,
        description='The official title on the ballot for this contest, only where available.',
    )
    candidates: Optional[List[Candidate]] = Field(
        None, description='The candidate choices for this contest.'
    )
    district: Optional[ElectoralDistrict] = Field(
        None,
        description='Information about the electoral district that this contest is in.',
    )
    electorateSpecifications: Optional[str] = Field(
        None,
        description='A description of any additional eligibility requirements for voting in this contest.',
    )
    level: Optional[List[LevelEnum]] = Field(
        None,
        description='The levels of government of the office for this contest. There may be more than one in cases where a jurisdiction effectively acts at two different levels of government; for example, the mayor of the District of Columbia acts at "locality" level, but also effectively at both "administrative-area-2" and "administrative-area-1".',
    )
    numberElected: Optional[str] = Field(
        None,
        description='The number of candidates that will be elected to office in this contest.',
    )
    numberVotingFor: Optional[str] = Field(
        None,
        description='The number of candidates that a voter may vote for in this contest.',
    )
    office: Optional[str] = Field(
        None, description='The name of the office for this contest.'
    )
    primaryParties: Optional[List[str]] = Field(
        None,
        description='If this is a partisan election, the name of the party/parties it is for.',
    )
    referendumBallotResponses: Optional[List[str]] = Field(
        None,
        description='The set of ballot responses for the referendum. A ballot response represents a line on the ballot. Common examples might include "yes" or "no" for referenda. This field is only populated for contests of type \'Referendum\'.',
    )
    referendumBrief: Optional[str] = Field(
        None,
        description="Specifies a short summary of the referendum that is typically on the ballot below the title but above the text. This field is only populated for contests of type 'Referendum'.",
    )
    referendumConStatement: Optional[str] = Field(
        None,
        description="A statement in opposition to the referendum. It does not necessarily appear on the ballot. This field is only populated for contests of type 'Referendum'.",
    )
    referendumEffectOfAbstain: Optional[str] = Field(
        None,
        description="Specifies what effect abstaining (not voting) on the proposition will have (i.e. whether abstaining is considered a vote against it). This field is only populated for contests of type 'Referendum'.",
    )
    referendumPassageThreshold: Optional[str] = Field(
        None,
        description='The threshold of votes that the referendum needs in order to pass, e.g. "two-thirds". This field is only populated for contests of type \'Referendum\'.',
    )
    referendumProStatement: Optional[str] = Field(
        None,
        description="A statement in favor of the referendum. It does not necessarily appear on the ballot. This field is only populated for contests of type 'Referendum'.",
    )
    referendumSubtitle: Optional[str] = Field(
        None,
        description="A brief description of the referendum. This field is only populated for contests of type 'Referendum'.",
    )
    referendumText: Optional[str] = Field(
        None,
        description="The full text of the referendum. This field is only populated for contests of type 'Referendum'.",
    )
    referendumTitle: Optional[str] = Field(
        None,
        description="The title of the referendum (e.g. 'Proposition 42'). This field is only populated for contests of type 'Referendum'.",
    )
    referendumUrl: Optional[str] = Field(
        None,
        description="A link to the referendum. This field is only populated for contests of type 'Referendum'.",
    )
    roles: Optional[List[Role]] = Field(
        None, description='The roles which this office fulfills.'
    )
    sources: Optional[List[Source]] = Field(
        None,
        description='A list of sources for this contest. If multiple sources are listed, the data has been aggregated from those sources.',
    )
    special: Optional[str] = Field(
        None,
        description='"Yes" or "No" depending on whether this a contest being held outside the normal election cycle.',
    )
    type: Optional[str] = Field(
        None,
        description="The type of contest. Usually this will be 'General', 'Primary', or 'Run-off' for contests with candidates. For referenda this will be 'Referendum'. For Retention contests this will typically be 'Retention'.",
    )


class DivisionSearchResponse(BaseModel):
    kind: Optional[str] = Field(
        'civicinfo#divisionSearchResponse',
        description='Identifies what kind of resource this is. Value: the fixed string "civicinfo#divisionSearchResponse".',
    )
    results: Optional[List[DivisionSearchResult]] = None


class FeatureIdProto(BaseModel):
    cellId: Optional[str] = Field(
        None,
        description='The S2CellId corresponding to the approximate location of this feature as of when it was first created. This can be of variable accuracy, ranging from the exact centroid of the feature at creation, a very large S2 Cell, or even being completely randomized for locationless features. Cell ids have the nice property that they follow a space-filling curve over the surface of the earth. (See s2cellid.h for details.) WARNING: Clients should only use cell IDs to perform spatial locality optimizations. There is no strict guarantee that the cell ID of a feature is related to the current geometry of the feature in any way.',
    )
    fprint: Optional[str] = Field(
        None,
        description='A 64-bit fingerprint used to identify features. Most clients should rely on MapFacts or OneRing to choose fingerprints. If creating new fprints, the strategy should be chosen so that the chance of collision is remote or non-existent, and the distribution should be reasonably uniform. For example, if the source data assigns unique ids to features, then a fingerprint of the provider name, version, and source id is sufficient.',
    )
    temporaryData: Optional[MessageSet] = Field(
        None,
        description='A place for clients to attach arbitrary data to a feature ID. Never set in MapFacts.',
    )


class GeocodingSummary(BaseModel):
    addressUnderstood: Optional[bool] = Field(
        None,
        description='Represents the best estimate of whether or not the input address was fully understood and the address is correctly componentized. Mirrors the same-name field in geostore.staging.AddressLinkupScoringProto.',
    )
    featureId: Optional[FeatureIdProto] = Field(
        None, description='The ID of the FeatureProto returned by the geocoder'
    )
    featureType: Optional[FeatureType] = Field(
        None,
        description='The feature type for the FeatureProto returned by the geocoder',
    )
    positionPrecisionMeters: Optional[float] = Field(
        None,
        description='Precision of the center point (lat/long) of the geocoded FeatureProto',
    )
    queryString: Optional[str] = Field(
        None, description='The query sent to the geocoder'
    )


class Office(BaseModel):
    divisionId: Optional[str] = Field(
        None,
        description='The OCD ID of the division with which this office is associated.',
    )
    levels: Optional[List[Level]] = Field(
        None,
        description='The levels of government of which this office is part. There may be more than one in cases where a jurisdiction effectively acts at two different levels of government; for example, the mayor of the District of Columbia acts at "locality" level, but also effectively at both "administrative-area-2" and "administrative-area-1".',
    )
    name: Optional[str] = Field(
        None, description='The human-readable name of the office.'
    )
    officialIndices: Optional[List[int]] = Field(
        None,
        description='List of indices in the officials array of people who presently hold this office.',
    )
    roles: Optional[List[Role]] = Field(
        None,
        description='The roles which this office fulfills. Roles are not meant to be exhaustive, or to exactly specify the entire set of responsibilities of a given office, but are meant to be rough categories that are useful for general selection from or sorting of a list of offices.',
    )
    sources: Optional[List[Source]] = Field(
        None,
        description='A list of sources for this office. If multiple sources are listed, the data has been aggregated from those sources.',
    )


class Official(BaseModel):
    address: Optional[List[SimpleAddressType]] = Field(
        None, description='Addresses at which to contact the official.'
    )
    channels: Optional[List[Channel]] = Field(
        None, description='A list of known (social) media channels for this official.'
    )
    emails: Optional[List[str]] = Field(
        None, description='The direct email addresses for the official.'
    )
    geocodingSummaries: Optional[List[GeocodingSummary]] = Field(
        None, description="Detailed summary about the official's address's geocoding"
    )
    name: Optional[str] = Field(None, description="The official's name.")
    party: Optional[str] = Field(
        None, description='The full name of the party the official belongs to.'
    )
    phones: Optional[List[str]] = Field(
        None, description="The official's public contact phone numbers."
    )
    photoUrl: Optional[str] = Field(
        None, description='A URL for a photo of the official.'
    )
    urls: Optional[List[str]] = Field(
        None, description="The official's public website URLs."
    )


class PollingLocation(BaseModel):
    address: Optional[SimpleAddressType] = Field(
        None, description='The address of the location.'
    )
    endDate: Optional[str] = Field(
        None,
        description='The last date that this early vote site or drop off location may be used. This field is not populated for polling locations.',
    )
    latitude: Optional[float] = Field(
        None,
        description='Latitude of the location, in degrees north of the equator. Note this field may not be available for some locations.',
    )
    longitude: Optional[float] = Field(
        None,
        description='Longitude of the location, in degrees east of the Prime Meridian. Note this field may not be available for some locations.',
    )
    name: Optional[str] = Field(
        None,
        description='The name of the early vote site or drop off location. This field is not populated for polling locations.',
    )
    notes: Optional[str] = Field(
        None,
        description='Notes about this location (e.g. accessibility ramp or entrance to use).',
    )
    pollingHours: Optional[str] = Field(
        None, description='A description of when this location is open.'
    )
    sources: Optional[List[Source]] = Field(
        None,
        description='A list of sources for this location. If multiple sources are listed the data has been aggregated from those sources.',
    )
    startDate: Optional[str] = Field(
        None,
        description='The first date that this early vote site or drop off location may be used. This field is not populated for polling locations.',
    )
    voterServices: Optional[str] = Field(
        None,
        description='The services provided by this early vote site or drop off location. This field is not populated for polling locations.',
    )


class RepresentativeInfoData(BaseModel):
    divisions: Optional[Dict[str, GeographicDivision]] = Field(
        None,
        description='A map of political geographic divisions that contain the requested address, keyed by the unique Open Civic Data identifier for this division.',
    )
    offices: Optional[List[Office]] = Field(
        None,
        description='Elected offices referenced by the divisions listed above. Will only be present if includeOffices was true in the request.',
    )
    officials: Optional[List[Official]] = Field(
        None,
        description='Officials holding the offices listed above. Will only be present if includeOffices was true in the request.',
    )


class RepresentativeInfoResponse(BaseModel):
    divisions: Optional[Dict[str, GeographicDivision]] = Field(
        None,
        description='A map of political geographic divisions that contain the requested address, keyed by the unique Open Civic Data identifier for this division.',
    )
    kind: Optional[str] = Field(
        'civicinfo#representativeInfoResponse',
        description='Identifies what kind of resource this is. Value: the fixed string "civicinfo#representativeInfoResponse".',
    )
    normalizedInput: Optional[SimpleAddressType] = Field(
        None, description='The normalized version of the requested address'
    )
    offices: Optional[List[Office]] = Field(
        None,
        description='Elected offices referenced by the divisions listed above. Will only be present if includeOffices was true in the request.',
    )
    officials: Optional[List[Official]] = Field(
        None,
        description='Officials holding the offices listed above. Will only be present if includeOffices was true in the request.',
    )


class AdministrationRegion(BaseModel):
    electionAdministrationBody: Optional[AdministrativeBody] = Field(
        None, description='The election administration body for this area.'
    )
    local_jurisdiction: Optional[AdministrationRegion] = Field(
        None,
        description='The city or county that provides election information for this voter. This object can have the same elements as state.',
    )
    name: Optional[str] = Field(None, description='The name of the jurisdiction.')
    sources: Optional[List[Source]] = Field(
        None,
        description='A list of sources for this area. If multiple sources are listed the data has been aggregated from those sources.',
    )


class VoterInfoResponse(BaseModel):
    contests: Optional[List[Contest]] = Field(
        None, description="Contests that will appear on the voter's ballot."
    )
    dropOffLocations: Optional[List[PollingLocation]] = Field(
        None,
        description='Locations where a voter is eligible to drop off a completed ballot. The voter must have received and completed a ballot prior to arriving at the location. The location may not have ballots available on the premises. These locations could be open on or before election day as indicated in the pollingHours field.',
    )
    earlyVoteSites: Optional[List[PollingLocation]] = Field(
        None,
        description='Locations where the voter is eligible to vote early, prior to election day.',
    )
    election: Optional[Election] = Field(
        None, description='The election that was queried.'
    )
    kind: Optional[str] = Field(
        'civicinfo#voterInfoResponse',
        description='Identifies what kind of resource this is. Value: the fixed string "civicinfo#voterInfoResponse".',
    )
    mailOnly: Optional[bool] = Field(
        None,
        description='Specifies whether voters in the precinct vote only by mailing their ballots (with the possible option of dropping off their ballots as well).',
    )
    normalizedInput: Optional[SimpleAddressType] = Field(
        None, description='The normalized version of the requested address'
    )
    otherElections: Optional[List[Election]] = Field(
        None,
        description='When there are multiple elections for a voter address, the otherElections field is populated in the API response and there are two possibilities: 1. If the earliest election is not the intended election, specify the election ID of the desired election in a second API request using the electionId field. 2. If these elections occur on the same day, the API doesn?t return any polling location, contest, or election official information to ensure that an additional query is made. For user-facing applications, we recommend displaying these elections to the user to disambiguate. A second API request using the electionId field should be made for the election that is relevant to the user.',
    )
    pollingLocations: Optional[List[PollingLocation]] = Field(
        None,
        description='Locations where the voter is eligible to vote on election day.',
    )
    precinctId: Optional[str] = None
    precincts: Optional[List[Precinct]] = Field(
        None,
        description='The precincts that match this voter\'s address. Will only be returned for project IDs which have been whitelisted as "partner projects".',
    )
    state: Optional[List[AdministrationRegion]] = Field(
        None,
        description='Local Election Information for the state that the voter votes in. For the US, there will only be one element in this array.',
    )


AdministrationRegion.model_rebuild()
